// models/Product.js - defines product and category schema shapes and helpers

export const PRODUCT_CATEGORIES = [
  { value: 'flowers', label: 'Crochet Flowers', description: 'Single crochet stems and floral keepsakes.', sort_order: 1, is_active: true },
  { value: 'bouquets', label: 'Crochet Bouquets', description: 'Gift-ready handmade bouquets.', sort_order: 2, is_active: true },
  { value: 'keychains', label: 'Crochet Keychains', description: 'Small charms and everyday accessories.', sort_order: 3, is_active: true },
  { value: 'scrunchies', label: 'Crochet Scrunchies', description: 'Soft handmade hair accessories.', sort_order: 4, is_active: true },
  { value: 'gifts', label: 'Handmade Gifts', description: 'Personalized crochet gifts.', sort_order: 5, is_active: true },
  { value: 'custom', label: 'Custom Orders', description: 'Made-to-order crochet requests.', sort_order: 6, is_active: true },
]

export const PRODUCT_STATUS = {
  ACTIVE: 'active',
  DRAFT: 'draft',
  OUT_OF_STOCK: 'out_of_stock',
}

export const createCategoryDTO = (raw = {}) => ({
  id: raw.id || null,
  value: raw.value || raw.slug || '',
  label: raw.label || raw.name || '',
  description: raw.description || '',
  sort_order: raw.sort_order ?? 0,
  is_active: raw.is_active ?? true,
  created_at: raw.created_at || null,
  updated_at: raw.updated_at || null,
})

export const createProductDTO = (raw = {}) => ({
  id: raw.id || null,
  name: raw.name || '',
  description: raw.description || '',
  price: raw.price || 0,
  compare_price: raw.compare_price || null,
  category: raw.category || '',
  images: raw.images || [],
  stock_qty: raw.stock_qty ?? 1,
  status: raw.status || PRODUCT_STATUS.ACTIVE,
  is_featured: raw.is_featured || false,
  is_custom: raw.is_custom || false,
  yarn_type: raw.yarn_type || '',
  color_options: raw.color_options || [],
  care_instructions: raw.care_instructions || '',
  tags: raw.tags || [],
  created_at: raw.created_at || null,
  updated_at: raw.updated_at || null,
})

export const isOnSale = (product) =>
  product.compare_price && product.compare_price > product.price

export const discountPercent = (product) => {
  if (!isOnSale(product)) return 0
  return Math.round(((product.compare_price - product.price) / product.compare_price) * 100)
}

export const DEFAULT_PRODUCTS = [
  {
    id: 'prod-1',
    name: 'Everlasting Pastel Tulip & Daisy Bouquet',
    description: 'A breathtaking handcrafted bouquet featuring soft pastel tulips, daisies, and lavender sprigs tied with raw-edge cotton ribbon in textured kraft paper. Guaranteed to never wilt.',
    price: 899,
    compare_price: 1099,
    category: 'bouquets',
    images: ['/images/hero_bouquet.jpg'],
    stock_qty: 6,
    status: 'active',
    is_featured: true,
    is_custom: true,
    yarn_type: '100% Premium Milk Cotton',
    color_options: ['Soft Blush & Cream', 'Lilac & Sage', 'Buttercup & Peach'],
    care_instructions: 'Keep dry. Dust gently with a soft brush when needed.',
    tags: ['bouquet', 'tulip', 'everlasting', 'gift', 'popular'],
    created_at: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-2',
    name: 'Potted Sunflower & Daisy Bloom Keepsake',
    description: 'Miniature everlasting potted garden piece in a ceramic terracotta finish. Adds cheerful, permanent sunshine to bedside tables, study desks, and workspace setups.',
    price: 449,
    compare_price: 549,
    category: 'bouquets',
    images: ['/images/potted_bloom.jpg'],
    stock_qty: 9,
    status: 'active',
    is_featured: true,
    is_custom: true,
    yarn_type: 'Milk Cotton Yarn',
    color_options: ['Sunny Sunflower', 'Daisy Meadow', 'Warm Terracotta'],
    care_instructions: 'Keep away from direct water. Spot clean if needed.',
    tags: ['flowerpot', 'sunflower', 'desk-decor', 'bestseller'],
    created_at: '2025-01-02T00:00:00.000Z',
  },
  {
    id: 'prod-3',
    name: 'Daisy Flower Stem Bookmark',
    description: 'Delicate handmade crochet daisy flower bookmark with leafy green stem and sweet scalloped petals. Designed to lay flat between pages without bending book spines.',
    price: 199,
    compare_price: 249,
    category: 'flowers',
    images: ['/images/floral_bookmark_hd.jpg'],
    stock_qty: 14,
    status: 'active',
    is_featured: true,
    is_custom: false,
    yarn_type: '100% Fine Combed Cotton',
    color_options: ['Classic White & Yellow', 'Pastel Pink & Sage', 'Lilac & Leaf'],
    care_instructions: 'Gentle hand wash in cold water, reshape and dry flat.',
    tags: ['bookmark', 'daisy', 'stationery', 'floral', 'gift-favorite'],
    created_at: '2025-01-03T00:00:00.000Z',
  },
  {
    id: 'prod-4',
    name: 'Sweet Bunny Amigurumi Plush Keepsake',
    description: 'Ultra-soft handmade amigurumi bunny stuffed with premium hypoallergenic polyfill. Features hand-stitched floral collar and velvety plush ears.',
    price: 549,
    compare_price: 699,
    category: 'gifts',
    images: ['/images/amigurumi_bunny.jpg'],
    stock_qty: 5,
    status: 'active',
    is_featured: true,
    is_custom: true,
    yarn_type: 'Velvet Chenille & Milk Cotton',
    color_options: ['Oatmeal Cream', 'Blush Pink', 'Dusty Lavender'],
    care_instructions: 'Gentle spot clean with damp cloth and mild baby soap.',
    tags: ['amigurumi', 'plushie', 'bunny', 'keepsake'],
    created_at: '2025-01-04T00:00:00.000Z',
  },
  {
    id: 'prod-5',
    name: 'Aesthetic Gift Box & Handwritten Card Set',
    description: 'Artisan gift packaging box lined with tissue paper, dried botanical sprig, authentic wax seal stamp, and your personalized message hand-calligraphed.',
    price: 249,
    compare_price: 329,
    category: 'gifts',
    images: ['/images/gift_packaging.jpg'],
    stock_qty: 25,
    status: 'active',
    is_featured: true,
    is_custom: true,
    yarn_type: 'Kraft Board & Satin Ribbon',
    color_options: ['Natural Kraft & Terracotta', 'Ivory & Olive'],
    care_instructions: 'Keep dry.',
    tags: ['gift-set', 'packaging', 'keepsake', 'card'],
    created_at: '2025-01-05T00:00:00.000Z',
  },
  {
    id: 'prod-6',
    name: 'Sunflower Charm Keychain',
    description: 'Bright miniature sunflower keychain with gold-tone carabiner clip and split ring. Crafted with tight, durable stitches that maintain shape.',
    price: 169,
    compare_price: 219,
    category: 'keychains',
    images: ['/images/flower_keychain.jpg'],
    stock_qty: 16,
    status: 'active',
    is_featured: true,
    is_custom: false,
    yarn_type: 'Milk Cotton Yarn',
    color_options: ['Golden Amber', 'Sunny Yellow'],
    care_instructions: 'Spot clean with cool water.',
    tags: ['keychain', 'sunflower', 'bag-charm'],
    created_at: '2025-01-06T00:00:00.000Z',
  },
  {
    id: 'prod-7',
    name: 'Coquette Bow Charm Keychain',
    description: 'Dainty hand-knitted ribbon bow charm with dangling loops and golden hardware. Aesthetic accessory to clip onto totes, shoulder bags, and keys.',
    price: 149,
    compare_price: 199,
    category: 'keychains',
    images: ['/images/bow_keychain.jpg'],
    stock_qty: 18,
    status: 'active',
    is_featured: false,
    is_custom: false,
    yarn_type: 'Soft Acrylic & Cotton',
    color_options: ['Dusty Rose', 'Cream Ivory', 'Soft Sage'],
    care_instructions: 'Hand wash gently in cool water.',
    tags: ['bow', 'keychain', 'charm', 'coquette'],
    created_at: '2025-01-07T00:00:00.000Z',
  },
  {
    id: 'prod-8',
    name: 'Puff Petal Flower Keychain',
    description: 'Fluffy 3D puff stitch bloom charm with contrasting center button. Bouncy, tactile, and crafted with high durability.',
    price: 179,
    compare_price: 229,
    category: 'keychains',
    images: ['/images/puff_flower_keychain.jpg'],
    stock_qty: 11,
    status: 'active',
    is_featured: false,
    is_custom: false,
    yarn_type: 'Chunky Cotton Yarn',
    color_options: ['Berry & Ivory', 'Blush & Lemon', 'Lavender & White'],
    care_instructions: 'Gently hand wash in cool water.',
    tags: ['puff flower', 'bag charm', 'keychain'],
    created_at: '2025-01-08T00:00:00.000Z',
  },
  {
    id: 'prod-9',
    name: 'Pastel Daisy Charm Keychain',
    description: 'Soft dimensional pastel daisy with flexible petals and antique brass/gold clip. An uplifting everyday companion for backpacks.',
    price: 149,
    compare_price: 189,
    category: 'keychains',
    images: ['/images/daisy_keychain.jpg'],
    stock_qty: 12,
    status: 'active',
    is_featured: false,
    is_custom: false,
    yarn_type: 'Milk Cotton',
    color_options: ['Sky Blue', 'Mint Green', 'Peach Coral'],
    care_instructions: 'Spot clean with damp cloth.',
    tags: ['daisy', 'keychain', 'pastel'],
    created_at: '2025-01-09T00:00:00.000Z',
  },
  {
    id: 'prod-10',
    name: 'Handcrafted Ruffle Flower Hair Scrunchie',
    description: 'Gentle on fine hair with thick interior elastic wrapped in soft crochet loops and miniature floral accents. Prevents hair breakage while looking chic.',
    price: 189,
    compare_price: 249,
    category: 'scrunchies',
    images: ['https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80'],
    stock_qty: 15,
    status: 'active',
    is_featured: false,
    is_custom: false,
    yarn_type: 'Silk Bamboo & Cotton',
    color_options: ['Earthy Sage', 'Dusty Rose', 'Oatmeal'],
    care_instructions: 'Gentle hand wash in cool water, lay flat to dry.',
    tags: ['scrunchie', 'hair', 'accessories', 'gentle'],
    created_at: '2025-01-10T00:00:00.000Z',
  },
]
